ALTER TABLE CUSTOMER
ADD CONSTRAINT FOREIGN KEY (customer_ID) REFERENCES ADDRESS(address_ID);
ALTER TABLE CUSTOMER
ADD CONSTRAINT FOREIGN KEY (customer_ID) REFERENCES PHONE_NO(phone_ID);
ALTER TABLE CUSTOMER
ADD CONSTRAINT FOREIGN KEY (customer_ID) REFERENCES HISTORY(history_ID);


ALTER TABLE REQUEST
ADD CONSTRAINT FOREIGN KEY (customer_ID) REFERENCES CUSTOMER(customer_ID);
ALTER TABLE REQUEST
ADD CONSTRAINT FOREIGN KEY (request_ID) REFERENCES SAMPLE(sample_ID);
ALTER TABLE REQUEST
ADD CONSTRAINT FOREIGN KEY (request_ID) REFERENCES PAYMENT(payment_ID);
ALTER TABLE REQUEST
ADD CONSTRAINT FOREIGN KEY (request_ID) REFERENCES RESULT(result_ID);


ALTER TABLE RESULT
ADD CONSTRAINT FOREIGN KEY (customer_history_ID) REFERENCES HISTORY(history_ID);

